[package]
name = "kesko_physics"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.0"
rapier3d = "0.14.0"
nalgebra = "0.31.0"
fnv = "1.0.7"
crossbeam = "0.8.1"

[profile.dev.package.rapier3d]
opt-level = 3
