[workspace]
members = ["core", "python"]

[package]
name = "nora"
version = "0.1.0"
edition = "2018"

[lib]
name = "nora_lib"
path = "src/lib.rs"

[dependencies.bevy]
version = "0.5"
default-features=false
features = ["bevy_gltf", "bevy_winit", "bevy_wgpu", "render", "bevy_dynamic_plugin", "png", "hdr", "x11"]
