[workspace]
members = ["core", "python"]

[package]
name = "nora"
version = "0.1.0"
edition = "2021"

[lib]
name = "nora_lib"
path = "src/lib.rs"

[dependencies.bevy]
version = "0.6.1"
default-features=false
features = ["bevy_gltf", "bevy_winit", "render", "bevy_dynamic_plugin", "png", "hdr", "x11"]

[dependencies.heron]
version = "2.3.0"
features = ["3d"]
