[workspace]
members = [
    "crates/kesko_core",
    "crates/kesko_physics",
    "crates/kesko_raycast",
    "crates/kesko_python",
    "crates/kesko_object_interaction",
]

[package]
name = "kesko"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.0"
bevy_egui = "0.16.0"
kesko_physics = { version = "0.1.0", path = "crates/kesko_physics" }
kesko_core = { version = "0.1.0", path = "crates/kesko_core" }
kesko_object_interaction = { version = "0.1.0", path = "crates/kesko_object_interaction"}
kesko_raycast = { version = "0.1.0", path = "crates/kesko_raycast"}