[package]
name = "pykesko"
version = "0.1.0"
edition = "2021"

[lib]
name = "pykesko"
crate-type = ["cdylib"]

[dependencies]
bevy = { version = "0.8.1", default-features = false, features = ["render", "bevy_winit", "bevy_scene", "x11"] }
kesko = { path = "../kesko"}
pyo3 = { version = "0.17.2", features = ["extension-module"] }
serde = { version = "1.0.137" }
serde_json = "1.0.81"
