[package]
name = "nora_object_interaction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
nora_raycast = {version="0.1.0", path="../nora_raycast"}