[package]
name = "nora_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "pynora"
crate-type = ["cdylib"]


[dependencies]
nora = { path= "../.." }
nora_core = { path= "../core" }
pyo3 = { version = "0.14.1", features = ["extension-module"] }
