[package]
name = "kesko_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.0"
bevy_egui = "0.16.0"
kesko_physics = { version = "0.1.0", path = "../kesko_physics" }
kesko_object_interaction = { path = "../kesko_object_interaction"}
kesko_raycast = { path = "../kesko_raycast"}
