name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-kesko:
    name: "Build and test Kesko"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-04-20

      - name: Kesko - Build
        run: cargo build --verbose
        working-directory: ./kesko

      - name: Kesko - Run tests
        run: cargo test --all --verbose
        working-directory: ./kesko

  build-pykesko:
    name: "Build and test PyKesko"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-04-20

      - name: PyKesko - Build
        run: cargo build --verbose
        working-directory: ./pykesko

      - name: PyKesko - Run tests
        run: cargo test --all --verbose
        working-directory: ./pykesko
